# real data
dataset: ImageNet1K
real_data_path: ./dataset/ImageNet1K/

# synthetic data
ipc: 10
im_size: [224, 224]

# agent model
model_name: ResNet-18-BN
stu_use_torchvision: true
tea_use_torchvision: true
teacher_dir: ./teacher_models
teacher_model_names: [ResNet-18-BN]

# syntheticdata augmentation
data_aug_func: cutmix
aug_params:
    beta: 1.0
use_zca: false

custom_train_trans: 
  - name: RandomResizedCrop
    args:
      size: 64
      scale: [0.08, 1.0]
  - name: RandomHorizontalFlip
    args:
      p: 0.5
  - name: ToTensor
  - name: Normalize
    args:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

custom_val_trans:
  - name: Resize
    args:
      size: 256
  - name: CenterCrop
    args:
      size: 64
  - name: ToTensor
  - name: Normalize
    args:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# soft label settings
label_type: soft
soft_label_mode: M
soft_label_criterion: kl
loss_fn_kwargs:
    temperature: 1.0
    scale_loss: false

# training specifics
optimizer: adamw
lr_scheduler: cosine
weight_decay: 0.01
momentum: 0.9
num_eval: 5
num_epochs: 300
num_workers: 4
device: cuda
dist: true
batch_size: 1024
random_data_path: ./random_data/my_method/ImageNet1K/IPC10/
random_data_format: image

# save path
save_path: ./my_method_ars_scores.csv
