dataset: "CIFAR10"
real_data_path: "./dataset/"
ipc: 10
model_name: "ConvNet-3"
data_aug_func: "dsa"
aug_params: {
    "prob_flip": 0.5,
    "ratio_rotate": 15.0,
    "saturation": 2.0,
    "brightness": 1.0,
    "contrast": 0.5,
    "ratio_scale": 1.2,
    "ratio_crop_pad": 0.125,
    "ratio_cutout": 0.5
}
soft_label_mode: "S"
soft_label_criterion: "sce"
optimizer: "sgd"
lr_scheduler: "step"
temperature: 20.0
weight_decay: 0.0005
momentum: 0.9
num_eval: 5
im_size: (32, 32)
num_epochs: 1000
use_zca: True
batch_size: 256
default_lr: 0.01
num_workers: 4
save_path: "./results/my_method_soft_label_scores.csv"
device: "cuda"
