dataset: "CIFAR10"
real_data_path: "./dataset/"
ipc: 10
model_name: "ConvNet-3"
data_aug_func: "cutmix"
aug_params: {"cutmix_p": 1.0}
soft_label_mode: "S"
soft_label_criterion: "kl"
optimizer: "sgd"
lr_scheduler: "cosine"
temperature: 20.0
weight_decay: 0.01
momentum: 0.9
num_eval: 5
im_size: (32, 32)
num_epochs: 300
use_zca: False
batch_size: 256
default_lr: 0.01
save_path: "./results/my_method_soft_label_scores.csv"
device: "cuda"